         const vocabularyData = [
           // --- 初級レベル (ID: 1 - 134) ---
           { id: "1", english: "Hello", japanese: "こんにちは", pronunciation: "həˈloʊ", level: "beginner", category: "挨拶", emoji: "👋" },
           { id: "2", english: "Thank you", japanese: "ありがとう", pronunciation: "θæŋk juː", level: "beginner", category: "挨拶", emoji: "🙏" },
           { id: "3", english: "Goodbye", japanese: "さようなら", pronunciation: "ɡʊdˈbaɪ", level: "beginner", category: "挨拶", emoji: "👋" },
           { id: "4", english: "Please", japanese: "お願いします", pronunciation: "pliːz", level: "beginner", category: "挨拶", emoji: "🙏" },
           { id: "5", english: "Yes", japanese: "はい", pronunciation: "jes", level: "beginner", category: "基本", emoji: "✅" },
           { id: "6", english: "No", japanese: "いいえ", pronunciation: "noʊ", level: "beginner", category: "基本", emoji: "❌" },
           { id: "7", english: "Good", japanese: "良い", pronunciation: "ɡʊd", level: "beginner", category: "形容詞", emoji: "👍" },
           { id: "8", english: "Bad", japanese: "悪い", pronunciation: "bæd", level: "beginner", category: "形容詞", emoji: "👎" },
           { id: "9", english: "Big", japanese: "大きい", pronunciation: "bɪɡ", level: "beginner", category: "形容詞", emoji: "🐘" },
           { id: "10", english: "Small", japanese: "小さい", pronunciation: "smɔːl", level: "beginner", category: "形容詞", emoji: "🐭" },
           { id: "11", english: "Hot", japanese: "暑い", pronunciation: "hɑːt", level: "beginner", category: "形容詞", emoji: "🔥" },
           { id: "12", english: "Cold", japanese: "寒い", pronunciation: "koʊld", level: "beginner", category: "形容詞", emoji: "❄️" },
           { id: "13", english: "Happy", japanese: "幸せな", pronunciation: "ˈhæpi", level: "beginner", category: "感情", emoji: "😊" },
           { id: "14", english: "Sad", japanese: "悲しい", pronunciation: "sæd", level: "beginner", category: "感情", emoji: "😢" },
           { id: "15", english: "Red", japanese: "赤", pronunciation: "red", level: "beginner", category: "色", emoji: "🔴" },
           { id: "16", english: "Blue", japanese: "青", pronunciation: "bluː", level: "beginner", category: "色", emoji: "🔵" },
           { id: "17", english: "Green", japanese: "緑", pronunciation: "ɡriːn", level: "beginner", category: "色", emoji: "🟢" },
           { id: "18", english: "Yellow", japanese: "黄色", pronunciation: "ˈjeloʊ", level: "beginner", category: "色", emoji: "🟡" },
           { id: "19", english: "Black", japanese: "黒", pronunciation: "blæk", level: "beginner", category: "色", emoji: "⚫" },
           { id: "20", english: "White", japanese: "白", pronunciation: "waɪt", level: "beginner", category: "色", emoji: "⚪" },
           { id: "21", english: "One", japanese: "1", pronunciation: "wʌn", level: "beginner", category: "数字", emoji: "1️⃣" },
           { id: "22", english: "Two", japanese: "2", pronunciation: "tuː", level: "beginner", category: "数字", emoji: "2️⃣" },
           { id: "23", english: "Three", japanese: "3", pronunciation: "θriː", level: "beginner", category: "数字", emoji: "3️⃣" },
           { id: "24", english: "Ten", japanese: "10", pronunciation: "ten", level: "beginner", category: "数字", emoji: "🔟" },
           { id: "25", english: "Mother", japanese: "母", pronunciation: "ˈmʌðər", level: "beginner", category: "家族", emoji: "👩" },
           { id: "26", english: "Father", japanese: "父", pronunciation: "ˈfɑːðər", level: "beginner", category: "家族", emoji: "👨" },
           { id: "27", english: "Sister", japanese: "姉妹", pronunciation: "ˈsɪstər", level: "beginner", category: "家族", emoji: "👧" },
           { id: "28", english: "Brother", japanese: "兄弟", pronunciation: "ˈbrʌðər", level: "beginner", category: "家族", emoji: "👦" },
           { id: "29", english: "Dog", japanese: "犬", pronunciation: "dɔːɡ", level: "beginner", category: "動物", emoji: "🐕" },
           { id: "30", english: "Cat", japanese: "猫", pronunciation: "kæt", level: "beginner", category: "動物", emoji: "🐈" },
           { id: "31", english: "Book", japanese: "本", pronunciation: "bʊk", level: "beginner", category: "学校", emoji: "📖" },
           { id: "32", english: "Pen", japanese: "ペン", pronunciation: "pen", level: "beginner", category: "学校", emoji: "✏️" },
           { id: "33", english: "School", japanese: "学校", pronunciation: "skuːl", level: "beginner", category: "学校", emoji: "🏫" },
           { id: "34", english: "Teacher", japanese: "先生", pronunciation: "ˈtiːtʃər", level: "beginner", category: "学校", emoji: "👨‍🏫" },
           { id: "35", english: "Student", japanese: "生徒", pronunciation: "ˈstuːdnt", level: "beginner", category: "学校", emoji: "🎓" },
           { id: "36", english: "Apple", japanese: "りんご", pronunciation: "ˈæpl", level: "beginner", category: "食べ物", emoji: "🍎" },
           { id: "37", english: "Water", japanese: "水", pronunciation: "ˈwɔːtər", level: "beginner", category: "食べ物", emoji: "💧" },
           { id: "38", english: "Bread", japanese: "パン", pronunciation: "bred", level: "beginner", category: "食べ物", emoji: "🍞" },
           { id: "39", english: "House", japanese: "家", pronunciation: "haʊs", level: "beginner", category: "場所", emoji: "🏠" },
           { id: "40", english: "Park", japanese: "公園", pronunciation: "pɑːrk", level: "beginner", category: "場所", emoji: "🏞️" },
           { id: "41", english: "Desk", japanese: "机", pronunciation: "デスク", level: "beginner", category: "家具", emoji: "🪑" },
           { id: "42", english: "Chair", japanese: "椅子", pronunciation: "チェア", level: "beginner", category: "家具", emoji: "🪑" },
           { id: "43", english: "Bag", japanese: "カバン", pronunciation: "バッグ", level: "beginner", category: "日用品", emoji: "👜" },
           { id: "44", english: "Shoes", japanese: "靴", pronunciation: "シューズ", level: "beginner", category: "衣類", emoji: "👟" },
           { id: "45", english: "Watch", japanese: "時計", pronunciation: "ウォッチ", level: "beginner", category: "日用品", emoji: "⌚" },
           { id: "46", english: "Sun", japanese: "太陽", pronunciation: "サン", level: "beginner", category: "自然", emoji: "☀️" },
           { id: "47", english: "Moon", japanese: "月", pronunciation: "ムーン", level: "beginner", category: "自然", emoji: "🌙" },
           { id: "48", english: "Star", japanese: "星", pronunciation: "スター", level: "beginner", category: "自然", emoji: "⭐" },
           { id: "49", english: "Sky", japanese: "空", pronunciation: "スカイ", level: "beginner", category: "自然", emoji: "☁️" },
           { id: "50", english: "Sea", japanese: "海", pronunciation: "スィー", level: "beginner", category: "自然", emoji: "🌊" },
           { id: "51", english: "Tree", japanese: "木", pronunciation: "トゥリー", level: "beginner", category: "自然", emoji: "🌳" },
           { id: "52", english: "Flower", japanese: "花", pronunciation: "フラワー", level: "beginner", category: "自然", emoji: "🌸" },
           { id: "53", english: "Bird", japanese: "鳥", pronunciation: "バード", level: "beginner", category: "動物", emoji: "🐦" },
           { id: "54", english: "Fish", japanese: "魚", pronunciation: "フィッシュ", level: "beginner", category: "動物", emoji: "🐟" },
           { id: "55", english: "Milk", japanese: "牛乳", pronunciation: "ミルク", level: "beginner", category: "飲み物", emoji: "🥛" },
           { id: "56", english: "Tea", japanese: "お茶", pronunciation: "ティー", level: "beginner", category: "飲み物", emoji: "🍵" },
           { id: "57", english: "Egg", japanese: "卵", pronunciation: "エッグ", level: "beginner", category: "食べ物", emoji: "🥚" },
           { id: "58", english: "Rice", japanese: "米/ご飯", pronunciation: "ライス", level: "beginner", category: "食べ物", emoji: "🍚" },
           { id: "59", english: "Meat", japanese: "肉", pronunciation: "ミート", level: "beginner", category: "食べ物", emoji: "🥩" },
           { id: "60", english: "Hand", japanese: "手", pronunciation: "ハンド", level: "beginner", category: "身体", emoji: "✋" },
           { id: "61", english: "Foot", japanese: "足", pronunciation: "フット", level: "beginner", category: "身体", emoji: "🦶" },
           { id: "62", english: "Head", japanese: "頭", pronunciation: "ヘッド", level: "beginner", category: "身体", emoji: "👤" },
           { id: "63", english: "Eye", japanese: "目", pronunciation: "アイ", level: "beginner", category: "身体", emoji: "👁️" },
           { id: "64", english: "Ear", japanese: "耳", pronunciation: "イア", level: "beginner", category: "身体", emoji: "👂" },
           { id: "65", english: "Mouth", japanese: "口", pronunciation: "マウス", level: "beginner", category: "身体", emoji: "👄" },
           { id: "66", english: "Nose", japanese: "鼻", pronunciation: "ノウズ", level: "beginner", category: "身体", emoji: "👃" },
           { id: "67", english: "Bike", japanese: "自転車", pronunciation: "バイク", level: "beginner", category: "乗り物", emoji: "🚲" },
           { id: "68", english: "Car", japanese: "車", pronunciation: "カー", level: "beginner", category: "乗り物", emoji: "🚗" },
           { id: "69", english: "Plane", japanese: "飛行機", pronunciation: "プレイン", level: "beginner", category: "乗り物", emoji: "✈️" },
           { id: "70", english: "Map", japanese: "地図", pronunciation: "マップ", level: "beginner", category: "日用品", emoji: "🗺️" },
           { id: "71", english: "Card", japanese: "カード", pronunciation: "カード", level: "beginner", category: "日用品", emoji: "💳" },
           { id: "72", english: "Coin", japanese: "硬貨", pronunciation: "コイン", level: "beginner", category: "お金", emoji: "🪙" },
           { id: "73", english: "Door", japanese: "ドア", pronunciation: "ドアー", level: "beginner", category: "家具", emoji: "🚪" },
           { id: "74", english: "Window", japanese: "窓", pronunciation: "ウィンドゥ", level: "beginner", category: "家具", emoji: "🪟" },
           { id: "75", english: "Box", japanese: "箱", pronunciation: "ボックス", level: "beginner", category: "日用品", emoji: "📦" },
           { id: "76", english: "Table", japanese: "テーブル", pronunciation: "テーブル", level: "beginner", category: "家具", emoji: "table" },
           { id: "77", english: "Food", japanese: "食べ物", pronunciation: "フード", level: "beginner", category: "生活", emoji: "🍱" },
           { id: "78", english: "Drink", japanese: "飲み物", pronunciation: "ドリンク", level: "beginner", category: "生活", emoji: "🥤" },
           { id: "79", english: "Walk", japanese: "歩く", pronunciation: "ウォーク", level: "beginner", category: "動詞", emoji: "🚶" },
           { id: "80", english: "Run", japanese: "走る", pronunciation: "ラン", level: "beginner", category: "動詞", emoji: "🏃" },
           { id: "81", english: "Eat", japanese: "食べる", pronunciation: "イート", level: "beginner", category: "動詞", emoji: "🍴" },
           { id: "82", english: "Sleep", japanese: "眠る", pronunciation: "スリープ", level: "beginner", category: "動詞", emoji: "😴" },
           { id: "83", english: "Read", japanese: "読む", pronunciation: "リード", level: "beginner", category: "動詞", emoji: "📖" },
           { id: "84", english: "Write", japanese: "書く", pronunciation: "ライト", level: "beginner", category: "動詞", emoji: "✍️" },
           { id: "85", english: "Listen", japanese: "聴く", pronunciation: "リスン", level: "beginner", category: "動詞", emoji: "🎧" },
           { id: "86", english: "See", japanese: "見る", pronunciation: "スィー", level: "beginner", category: "動詞", emoji: "👀" },
           { id: "87", english: "Talk", japanese: "話す", pronunciation: "トーク", level: "beginner", category: "動詞", emoji: "💬" },
           { id: "88", english: "Sing", japanese: "歌う", pronunciation: "スィング", level: "beginner", category: "動詞", emoji: "🎤" },
           { id: "89", english: "Dance", japanese: "踊る", pronunciation: "ダンス", level: "beginner", category: "動詞", emoji: "💃" },
           { id: "90", english: "Smile", japanese: "微笑む", pronunciation: "スマイル", level: "beginner", category: "感情", emoji: "😊" },
           { id: "91", english: "Play", japanese: "遊ぶ/演奏する", pronunciation: "プレイ", level: "beginner", category: "動詞", emoji: "🎮" },
           { id: "92", english: "Study", japanese: "勉強する", pronunciation: "スタディ", level: "beginner", category: "動詞", emoji: "📚" },
           { id: "93", english: "Help", japanese: "助ける", pronunciation: "ヘルプ", level: "beginner", category: "動詞", emoji: "🤝" },
           { id: "94", english: "Love", japanese: "愛する", pronunciation: "ラヴ", level: "beginner", category: "感情", emoji: "❤️" },
           { id: "95", english: "Friendship", japanese: "友情", pronunciation: "フレンドシップ", level: "beginner", category: "抽象", emoji: "🤝" },
           { id: "96", english: "Family", japanese: "家族", pronunciation: "ファミリー", level: "beginner", category: "家族", emoji: "👪" },
           { id: "97", english: "Time", japanese: "時間", pronunciation: "タイム", level: "beginner", category: "時間", emoji: "⏰" },
           { id: "98", english: "Day", japanese: "日", pronunciation: "デイ", level: "beginner", category: "時間", emoji: "☀️" },
           { id: "99", english: "Week", japanese: "週", pronunciation: "ウィーク", level: "beginner", category: "時間", emoji: "📅" },
           { id: "100", english: "Month", japanese: "月(期間)", pronunciation: "マンス", level: "beginner", category: "時間", emoji: "🗓️" },
           { id: "101", english: "Year", japanese: "年", pronunciation: "イアー", level: "beginner", category: "時間", emoji: "🎆" },
           { id: "102", english: "Spring", japanese: "春", pronunciation: "スプリング", level: "beginner", category: "自然", emoji: "🌸" },
           { id: "103", english: "Summer", japanese: "夏", pronunciation: "サマー", level: "beginner", category: "自然", emoji: "🌻" },
           { id: "104", english: "Autumn", japanese: "秋", pronunciation: "オータム", level: "beginner", category: "自然", emoji: "🍂" },
           { id: "105", english: "Winter", japanese: "冬", pronunciation: "ウィンター", level: "beginner", category: "自然", emoji: "❄️" },
           { id: "106", english: "Morning", japanese: "朝", pronunciation: "モーニング", level: "beginner", category: "時間", emoji: "🌅" },
           { id: "107", english: "Night", japanese: "夜", pronunciation: "ナイト", level: "beginner", category: "時間", emoji: "🌙" },
           { id: "108", english: "Today", japanese: "今日", pronunciation: "トゥデイ", level: "beginner", category: "時間", emoji: "📅" },
           { id: "109", english: "Tomorrow", japanese: "明日", pronunciation: "トゥモロー", level: "beginner", category: "時間", emoji: "🗓️" },
           { id: "110", english: "High", japanese: "高い", pronunciation: "ハイ", level: "beginner", category: "形容詞", emoji: "⛰️" },
           { id: "111", english: "Low", japanese: "低い", pronunciation: "ロウ", level: "beginner", category: "形容詞", emoji: "📉" },
           { id: "112", english: "New", japanese: "新しい", pronunciation: "ニュー", level: "beginner", category: "形容詞", emoji: "✨" },
           { id: "113", english: "Old", japanese: "古い", pronunciation: "オールド", level: "beginner", category: "形容詞", emoji: "🕰️" },
           { id: "114", english: "Long", japanese: "長い", pronunciation: "ロング", level: "beginner", category: "形容詞", emoji: "📏" },
           { id: "115", english: "Short", japanese: "短い", pronunciation: "ショート", level: "beginner", category: "形容詞", emoji: "✂️" },
           { id: "116", english: "Fast", japanese: "速い", pronunciation: "ファスト", level: "beginner", category: "形容詞", emoji: "⚡" },
           { id: "117", english: "Slow", japanese: "遅い", pronunciation: "スロウ", level: "beginner", category: "形容詞", emoji: "🐢" },
           { id: "118", english: "Easy", japanese: "簡単な", pronunciation: "イージー", level: "beginner", category: "形容詞", emoji: "✅" },
           { id: "119", english: "Difficult", japanese: "難しい", pronunciation: "ディフィカルト", level: "beginner", category: "形容詞", emoji: "🧩" },
           { id: "120", english: "Clean", japanese: "きれいな", pronunciation: "クリーン", level: "beginner", category: "形容詞", emoji: "✨" },
           { id: "121", english: "Dirty", japanese: "汚い", pronunciation: "ダーティ", level: "beginner", category: "形容詞", emoji: "🧹" },
           { id: "122", english: "Strong", japanese: "強い", pronunciation: "ストロング", level: "beginner", category: "形容詞", emoji: "💪" },
           { id: "123", english: "Weak", japanese: "弱い", pronunciation: "ウィーク", level: "beginner", category: "形容詞", emoji: "🍃" },
           { id: "124", english: "Bright", japanese: "明るい", pronunciation: "ブライト", level: "beginner", category: "形容詞", emoji: "💡" },
           { id: "125", english: "Dark", japanese: "暗い", pronunciation: "ダーク", level: "beginner", category: "形容詞", emoji: "🌑" },
           { id: "126", english: "Heavy", japanese: "重い", pronunciation: "ヘヴィ", level: "beginner", category: "形容詞", emoji: "🐘" },
           { id: "127", english: "Light", japanese: "軽い", pronunciation: "ライト", level: "beginner", category: "形容詞", emoji: "🪶" },
           { id: "128", english: "Rich", japanese: "豊かな", pronunciation: "リッチ", level: "beginner", category: "形容詞", emoji: "💰" },
           { id: "129", english: "Poor", japanese: "貧しい", pronunciation: "プア", level: "beginner", category: "形容詞", emoji: "🏚️" },
           { id: "130", english: "Early", japanese: "早い", pronunciation: "アーリー", level: "beginner", category: "形容詞", emoji: "⏰" },
           { id: "131", english: "Late", japanese: "遅い", pronunciation: "レイト", level: "beginner", category: "形容詞", emoji: "🐢" },
           { id: "132", english: "True", japanese: "本当の", pronunciation: "トゥルー", level: "beginner", category: "形容詞", emoji: "✔️" },
           { id: "133", english: "False", japanese: "間違いの", pronunciation: "フォルス", level: "beginner", category: "形容詞", emoji: "❌" },
           { id: "134", english: "Open", japanese: "開ける", pronunciation: "オープン", level: "beginner", category: "動詞", emoji: "🔓" },
         
           // --- 中級レベル (ID: 135 - 231) ---
           { id: "135", english: "Beautiful", japanese: "美しい", pronunciation: "ˈbjuːtɪfl", level: "intermediate", category: "形容詞", emoji: "✨" },
           { id: "136", english: "Important", japanese: "重要な", pronunciation: "ɪmˈpɔːrtnt", level: "intermediate", category: "形容詞", emoji: "⭐" },
           { id: "137", english: "Boring", japanese: "退屈な", pronunciation: "ˈbɔːrɪŋ", level: "intermediate", category: "形容詞", emoji: "😴" },
           { id: "138", english: "Breakfast", japanese: "朝食", pronunciation: "ˈbrekfəst", level: "intermediate", category: "食べ物", emoji: "🍳" },
           { id: "139", english: "Lunch", japanese: "昼食", pronunciation: "lʌntʃ", level: "intermediate", category: "食べ物", emoji: "🍱" },
           { id: "140", english: "Dinner", japanese: "夕食", pronunciation: "ˈdɪnər", level: "intermediate", category: "食べ物", emoji: "🍽️" },
           { id: "141", english: "Restaurant", japanese: "レストラン", pronunciation: "ˈrestrɑːnt", level: "intermediate", category: "場所", emoji: "🍴" },
           { id: "142", english: "Library", japanese: "図書館", pronunciation: "ˈlaɪbreri", level: "intermediate", category: "場所", emoji: "📚" },
           { id: "143", english: "Hospital", japanese: "病院", pronunciation: "ˈhɑːspɪtl", level: "intermediate", category: "場所", emoji: "🏥" },
           { id: "144", english: "Yesterday", japanese: "昨日", pronunciation: "ˈjestərdeɪ", level: "intermediate", category: "時間", emoji: "📅" },
           { id: "145", english: "Afternoon", japanese: "午後", pronunciation: "ˌæftərˈnuːn", level: "intermediate", category: "時間", emoji: "☀️" },
           { id: "146", english: "Evening", japanese: "夕方", pronunciation: "ˈiːvnɪŋ", level: "intermediate", category: "時間", emoji: "🌆" },
           { id: "147", english: "Music", japanese: "音楽", pronunciation: "ˈmjuːzɪk", level: "intermediate", category: "趣味", emoji: "🎵" },
           { id: "148", english: "Movie", japanese: "映画", pronunciation: "ˈmuːvi", level: "intermediate", category: "趣味", emoji: "🎬" },
           { id: "149", english: "Sports", japanese: "スポーツ", pronunciation: "spɔːrts", level: "intermediate", category: "趣味", emoji: "⚽" },
           { id: "150", english: "Soccer", japanese: "サッカー", pronunciation: "ˈsɑːkər", level: "intermediate", category: "趣味", emoji: "⚽" },
           { id: "151", english: "Basketball", japanese: "バスケットボール", pronunciation: "ˈbæskɪtbɔːl", level: "intermediate", category: "趣味", emoji: "🏀" },
           { id: "152", english: "Swimming", japanese: "水泳", pronunciation: "ˈswɪmɪŋ", level: "intermediate", category: "趣味", emoji: "🏊" },
           { id: "153", english: "People", japanese: "人々", pronunciation: "ˈpiːpl", level: "intermediate", category: "人", emoji: "👥" },
           { id: "154", english: "Doctor", japanese: "医者", pronunciation: "ˈdɑːktər", level: "intermediate", category: "職業", emoji: "👨‍⚕️" },
           { id: "155", english: "Nurse", japanese: "看護師", pronunciation: "nɜːrs", level: "intermediate", category: "職業", emoji: "👩‍⚕️" },
           { id: "156", english: "Weather", japanese: "天気", pronunciation: "ˈweðər", level: "intermediate", category: "天気", emoji: "🌤️" },
           { id: "157", english: "Sunny", japanese: "晴れ", pronunciation: "ˈsʌni", level: "intermediate", category: "天気", emoji: "☀️" },
           { id: "158", english: "Rainy", japanese: "雨", pronunciation: "ˈreɪni", level: "intermediate", category: "天気", emoji: "🌧️" },
           { id: "159", english: "Cloudy", japanese: "曇り", pronunciation: "ˈklaʊdi", level: "intermediate", category: "天気", emoji: "☁️" },
           { id: "160", english: "Station", japanese: "駅", pronunciation: "ˈsteɪʃn", level: "intermediate", category: "場所", emoji: "🚉" },
           { id: "161", english: "Train", japanese: "電車", pronunciation: "treɪn", level: "intermediate", category: "交通", emoji: "🚆" },
           { id: "162", english: "Bus", japanese: "バス", pronunciation: "bʌs", level: "intermediate", category: "交通", emoji: "🚌" },
           { id: "163", english: "Accident", japanese: "事故", pronunciation: "アクシデント", level: "intermediate", category: "社会", emoji: "⚠️" },
           { id: "164", english: "Believe", japanese: "信じる", pronunciation: "ビリーヴ", level: "intermediate", category: "感情", emoji: "🙏" },
           { id: "165", english: "Challenge", japanese: "挑戦", pronunciation: "チャレンジ", level: "intermediate", category: "生活", emoji: "🏆" },
           { id: "166", english: "Decision", japanese: "決定", pronunciation: "ディスィジョン", level: "intermediate", category: "思考", emoji: "⚖️" },
           { id: "167", english: "Education", japanese: "教育", pronunciation: "エデュケイション", level: "intermediate", category: "社会", emoji: "🏫" },
           { id: "168", english: "Fashion", japanese: "流行/ファッション", pronunciation: "ファッション", level: "intermediate", category: "生活", emoji: "👗" },
           { id: "169", english: "Government", japanese: "政府", pronunciation: "ガヴァメント", level: "intermediate", category: "政治", emoji: "🏛️" },
           { id: "170", english: "Health", japanese: "健康", pronunciation: "ヘルス", level: "intermediate", category: "身体", emoji: "🥗" },
           { id: "171", english: "Imagine", japanese: "想像する", pronunciation: "イマジン", level: "intermediate", category: "思考", emoji: "💭" },
           { id: "172", english: "Journey", japanese: "旅", pronunciation: "ジャーニー", level: "intermediate", category: "生活", emoji: "🛶" },
           { id: "173", english: "Language", japanese: "言語", pronunciation: "ラングウィッジ", level: "intermediate", category: "学問", emoji: "🗣️" },
           { id: "174", english: "Memory", japanese: "記憶", pronunciation: "メモリー", level: "intermediate", category: "思考", emoji: "🧠" },
           { id: "175", english: "Opinion", japanese: "意見", pronunciation: "オピニオン", level: "intermediate", category: "思考", emoji: "💬" },
           { id: "176", english: "Promise", japanese: "約束", pronunciation: "プロミス", level: "intermediate", category: "生活", emoji: "🤙" },
           { id: "177", english: "Quality", japanese: "品質/質", pronunciation: "クオリティ", level: "intermediate", category: "ビジネス", emoji: "💎" },
           { id: "178", english: "Reason", japanese: "理由", pronunciation: "リーズン", level: "intermediate", category: "思考", emoji: "❓" },
           { id: "179", english: "Service", japanese: "サービス/奉仕", pronunciation: "サービス", level: "intermediate", category: "ビジネス", emoji: "🛎️" },
           { id: "180", english: "Traffic", japanese: "交通", pronunciation: "トラフィック", level: "intermediate", category: "社会", emoji: "🚦" },
           { id: "181", english: "Value", japanese: "価値", pronunciation: "ヴァリュー", level: "intermediate", category: "思考", emoji: "⚖️" },
           { id: "182", english: "Wealth", japanese: "富", pronunciation: "ウェルス", level: "intermediate", category: "ビジネス", emoji: "💰" },
           { id: "183", english: "Activity", japanese: "活動", pronunciation: "アクティビティ", level: "intermediate", category: "生活", emoji: "🏃" },
           { id: "184", english: "Benefit", japanese: "利益/恩恵", pronunciation: "ベネフィット", level: "intermediate", category: "ビジネス", emoji: "🎁" },
           { id: "185", english: "Condition", japanese: "条件/状態", pronunciation: "コンディション", level: "intermediate", category: "状態", emoji: "🌡️" },
           { id: "186", english: "Degree", japanese: "度/程度", pronunciation: "ディグリー", level: "intermediate", category: "学問", emoji: "🌡️" },
           { id: "187", english: "Energy", japanese: "エネルギー", pronunciation: "エナジー", level: "intermediate", category: "科学", emoji: "🔋" },
           { id: "188", english: "Feature", japanese: "特徴/特色", pronunciation: "フィーチャー", level: "intermediate", category: "ビジネス", emoji: "🌟" },
           { id: "189", english: "Growth", japanese: "成長", pronunciation: "グロウス", level: "intermediate", category: "生活", emoji: "📈" },
           { id: "190", english: "Honest", japanese: "正直な", pronunciation: "オネスト", level: "intermediate", category: "性格", emoji: "😇" },
           { id: "191", english: "Influence", japanese: "影響", pronunciation: "インフルエンス", level: "intermediate", category: "抽象", emoji: "🌊" },
           { id: "192", english: "Judgment", japanese: "判断", pronunciation: "ジャッジメント", level: "intermediate", category: "思考", emoji: "⚖️" },
           { id: "193", english: "Kindness", japanese: "親切", pronunciation: "カインドネス", level: "intermediate", category: "性格", emoji: "❤️" },
           { id: "194", english: "Level", japanese: "水準/レベル", pronunciation: "レヴェル", level: "intermediate", category: "状態", emoji: "📊" },
           { id: "195", english: "Measure", japanese: "測る/対策", pronunciation: "メジャー", level: "intermediate", category: "科学", emoji: "📏" },
           { id: "196", english: "Notice", japanese: "気づく/通知", pronunciation: "ノーティス", level: "intermediate", category: "思考", emoji: "🔔" },
           { id: "197", english: "Object", japanese: "物体/目的/反対する", pronunciation: "オブジェクト", level: "intermediate", category: "抽象", emoji: "📦" },
           { id: "198", english: "Period", japanese: "期間/時代", pronunciation: "ピリオド", level: "intermediate", category: "時間", emoji: "⏳" },
           { id: "199", english: "Respect", japanese: "尊敬する", pronunciation: "リスペクト", level: "intermediate", category: "感情", emoji: "🙇" },
           { id: "200", english: "Situation", japanese: "状況", pronunciation: "スィチュエイション", level: "intermediate", category: "抽象", emoji: "📍" },
           { id: "201", english: "Task", japanese: "任務/仕事", pronunciation: "タスク", level: "intermediate", category: "ビジネス", emoji: "📝" },
           { id: "202", english: "Unit", japanese: "単位/個体", pronunciation: "ユニット", level: "intermediate", category: "科学", emoji: "📏" },
           { id: "203", english: "Variety", japanese: "多様性/種類", pronunciation: "ヴァライエティ", level: "intermediate", category: "抽象", emoji: "🎨" },
           { id: "204", english: "Worker", japanese: "労働者", pronunciation: "ワーカー", level: "intermediate", category: "職業", emoji: "👷" },
           { id: "205", english: "Young", japanese: "若い", pronunciation: "ヤング", level: "intermediate", category: "年齢", emoji: "👶" },
           { id: "206", english: "Zone", japanese: "地域/地帯", pronunciation: "ゾウン", level: "intermediate", category: "場所", emoji: "📍" },
           { id: "207", english: "Ability", japanese: "能力", pronunciation: "アビリティ", level: "intermediate", category: "抽象", emoji: "💪" },
           { id: "208", english: "Balance", japanese: "均衡/バランス", pronunciation: "バランス", level: "intermediate", category: "抽象", emoji: "⚖️" },
           { id: "209", english: "Comfort", japanese: "快適さ", pronunciation: "コンフォート", level: "intermediate", category: "感情", emoji: "🛋️" },
           { id: "210", english: "Damage", japanese: "損害/ダメージ", pronunciation: "ダメージ", level: "intermediate", category: "社会", emoji: "💥" },
           { id: "211", english: "Effect", japanese: "効果/影響", pronunciation: "エフェクト", level: "intermediate", category: "抽象", emoji: "✨" },
           { id: "212", english: "Failure", japanese: "失敗", pronunciation: "フェイリャー", level: "intermediate", category: "抽象", emoji: "❌" },
           { id: "213", english: "Goal", japanese: "目標/ゴール", pronunciation: "ゴール", level: "intermediate", category: "生活", emoji: "🥅" },
           { id: "214", english: "Hobby", japanese: "趣味", pronunciation: "ホビー", level: "intermediate", category: "生活", emoji: "🎨" },
           { id: "215", english: "Individual", japanese: "個人の/一個人の", pronunciation: "インディヴィジュアル", level: "intermediate", category: "人", emoji: "👤" },
           { id: "216", english: "Justice", japanese: "正義", pronunciation: "ジャスティス", level: "intermediate", category: "抽象", emoji: "⚖️" },
           { id: "217", english: "Lesson", japanese: "教訓/レッスン", pronunciation: "レスン", level: "intermediate", category: "学問", emoji: "📖" },
           { id: "218", english: "Method", japanese: "方法", pronunciation: "メソッド", level: "intermediate", category: "抽象", emoji: "🔬" },
           { id: "219", english: "Network", japanese: "網/ネットワーク", pronunciation: "ネットワーク", level: "intermediate", category: "科学", emoji: "🌐" },
           { id: "220", english: "Opportunity", japanese: "機会/チャンス", pronunciation: "オポチュニティ", level: "intermediate", category: "抽象", emoji: "🚪" },
           { id: "221", english: "Pressure", japanese: "圧力/プレッシャー", pronunciation: "プレッシャー", level: "intermediate", category: "感情", emoji: "🎈" },
           { id: "222", english: "Regular", japanese: "規則的な/通常の", pronunciation: "レギュラー", level: "intermediate", category: "状態", emoji: "📏" },
           { id: "223", english: "Support", japanese: "支持/支える", pronunciation: "サポート", level: "intermediate", category: "生活", emoji: "🤝" },
           { id: "224", english: "Theory", japanese: "理論", pronunciation: "スィアリー", level: "intermediate", category: "学問", emoji: "📚" },
           { id: "225", english: "Union", japanese: "結合/連帯", pronunciation: "ユニオン", level: "intermediate", category: "社会", emoji: "🤝" },
           { id: "226", english: "Volume", japanese: "音量/量", pronunciation: "ヴォリューム", level: "intermediate", category: "科学", emoji: "🔊" },
           { id: "227", english: "Weight", japanese: "重さ", pronunciation: "ウェイト", level: "intermediate", category: "科学", emoji: "⚖️" },
           { id: "228", english: "Youth", japanese: "青春/若さ", pronunciation: "ユース", level: "intermediate", category: "年齢", emoji: "🌅" },
           { id: "229", english: "Zero", japanese: "ゼロ/零", pronunciation: "ズィーロウ", level: "intermediate", category: "数字", emoji: "0️⃣" },
           { id: "230", english: "Action", japanese: "行動", pronunciation: "アクション", level: "intermediate", category: "生活", emoji: "🎬" },
           { id: "231", english: "Common", japanese: "共通の/普通の", pronunciation: "コモン", level: "intermediate", category: "形容詞", emoji: "🌐" },
         
           // --- 上級レベル (ID: 232 - 411) ---
           { id: "232", english: "Experience", japanese: "経験", pronunciation: "ɪkˈspɪriəns", level: "advanced", category: "抽象", emoji: "💭" },
           { id: "233", english: "Knowledge", japanese: "知識", pronunciation: "ˈnɑːlɪdʒ", level: "advanced", category: "抽象", emoji: "🧠" },
           { id: "234", english: "Environment", japanese: "環境", pronunciation: "ɪnˈvaɪrənmənt", level: "advanced", category: "抽象", emoji: "🌍" },
           { id: "235", english: "Technology", japanese: "技術", pronunciation: "tekˈnɑːlədʒi", level: "advanced", category: "抽象", emoji: "💻" },
           { id: "236", english: "Communication", japanese: "コミュニケーション", pronunciation: "kəˌmjuːnɪˈkeɪʃn", level: "advanced", category: "抽象", emoji: "💬" },
           { id: "237", english: "Understand", japanese: "理解する", pronunciation: "ˌʌndərˈstænd", level: "advanced", category: "動詞", emoji: "💡" },
           { id: "238", english: "Explain", japanese: "説明する", pronunciation: "ɪkˈspleɪn", level: "advanced", category: "動詞", emoji: "📝" },
           { id: "239", english: "Compare", japanese: "比較する", pronunciation: "kəmˈper", level: "advanced", category: "動詞", emoji: "⚖️" },
           { id: "240", english: "Describe", japanese: "描写する", pronunciation: "dɪˈskraɪb", level: "advanced", category: "動詞", emoji: "🖊️" },
           { id: "241", english: "Improve", japanese: "改善する", pronunciation: "ɪmˈpruːv", level: "advanced", category: "動詞", emoji: "📈" },
           { id: "242", english: "Achieve", japanese: "達成する", pronunciation: "əˈtʃiːv", level: "advanced", category: "動詞", emoji: "🎯" },
           { id: "243", english: "Succeed", japanese: "成功する", pronunciation: "səkˈsiːd", level: "advanced", category: "動詞", emoji: "🏆" },
           { id: "244", english: "Necessary", japanese: "必要な", pronunciation: "ˈnesəseri", level: "advanced", category: "形容詞", emoji: "❗" },
           { id: "245", english: "Possible", japanese: "可能な", pronunciation: "ˈpɑːsəbl", level: "advanced", category: "形容詞", emoji: "✔️" },
           { id: "246", english: "Impossible", japanese: "不可能な", pronunciation: "ɪmˈpɑːsəbl", level: "advanced", category: "形容詞", emoji: "🚫" },
           { id: "247", english: "Popular", japanese: "人気のある", pronunciation: "ˈpɑːpjələr", level: "advanced", category: "形容詞", emoji: "🔥" },
           { id: "248", english: "Famous", japanese: "有名な", pronunciation: "ˈfeɪməs", level: "advanced", category: "形容詞", emoji: "⭐" },
           { id: "249", english: "Modern", japanese: "現代的な", pronunciation: "ˈmɑːdərn", level: "advanced", category: "形容詞", emoji: "🏙️" },
           { id: "250", english: "Ancient", japanese: "古代の", pronunciation: "ˈeɪnʃənt", level: "advanced", category: "形容詞", emoji: "🏛️" },
           { id: "251", english: "Natural", japanese: "自然な", pronunciation: "ˈnætʃrəl", level: "advanced", category: "形容詞", emoji: "🌿" },
           { id: "252", english: "Wonderful", japanese: "素晴らしい", pronunciation: "ˈwʌndərfl", level: "advanced", category: "形容詞", emoji: "🌈" },
           { id: "253", english: "Convenient", japanese: "便利な", pronunciation: "kənˈviːniənt", level: "advanced", category: "形容詞", emoji: "👍" },
           { id: "254", english: "Although", japanese: "〜だけれども", pronunciation: "ɔːlˈðoʊ", level: "advanced", category: "接続詞", emoji: "🔄" },
           { id: "255", english: "However", japanese: "しかしながら", pronunciation: "haʊˈevər", level: "advanced", category: "接続詞", emoji: "↔️" },
           { id: "256", english: "Therefore", japanese: "それゆえに", pronunciation: "ˈðerfɔːr", level: "advanced", category: "接続詞", emoji: "➡️" },
           { id: "257", english: "Society", japanese: "社会", pronunciation: "səˈsaɪəti", level: "advanced", category: "抽象", emoji: "🏘️" },
           { id: "258", english: "Culture", japanese: "文化", pronunciation: "ˈkʌltʃər", level: "advanced", category: "抽象", emoji: "🎭" },
           { id: "259", english: "History", japanese: "歴史", pronunciation: "ˈhɪstri", level: "advanced", category: "抽象", emoji: "📜" },
           { id: "260", english: "Science", japanese: "科学", pronunciation: "ˈsaɪəns", level: "advanced", category: "抽象", emoji: "🔬" },
           { id: "261", english: "Future", japanese: "未来", pronunciation: "ˈfjuːtʃər", level: "advanced", category: "時間", emoji: "🚀" },
           { id: "262", english: "Analysis", japanese: "分析", pronunciation: "アナリスィス", level: "advanced", category: "学問", emoji: "🔍" },
           { id: "263", english: "Consequence", japanese: "結果/重要性", pronunciation: "コンスィクウェンス", level: "advanced", category: "抽象", emoji: "🌪️" },
           { id: "264", english: "Distribution", japanese: "分布/配分", pronunciation: "ディストリビューション", level: "advanced", category: "ビジネス", emoji: "📦" },
           { id: "265", english: "Environment", japanese: "環境", pronunciation: "インヴァイロメント", level: "advanced", category: "抽象", emoji: "🌿" },
           { id: "266", english: "Framework", japanese: "枠組み/構造", pronunciation: "フレイムワーク", level: "advanced", category: "ビジネス", emoji: "🏗️" },
           { id: "267", english: "Hypothesis", japanese: "仮説", pronunciation: "ハイポスィスィス", level: "advanced", category: "学問", emoji: "🧪" },
           { id: "268", english: "Innovation", japanese: "革新", pronunciation: "イノヴェイション", level: "advanced", category: "ビジネス", emoji: "💡" },
           { id: "269", english: "Justification", japanese: "正当化/弁明", pronunciation: "ジャスティフィケイション", level: "advanced", category: "思考", emoji: "⚖️" },
           { id: "270", english: "Maintenance", japanese: "維持/整備", pronunciation: "メインテナンス", level: "advanced", category: "生活", emoji: "🔧" },
           { id: "271", english: "Negotiation", pronunciation: "ニゴウシエイション", japanese: "交渉", level: "advanced", category: "ビジネス", emoji: "🤝" },
           { id: "272", english: "Observation", japanese: "観察", pronunciation: "オブザヴェイション", level: "advanced", category: "学問", emoji: "🔭" },
           { id: "273", english: "Perspective", japanese: "観点/見通し", pronunciation: "パースペクティヴ", level: "advanced", category: "思考", emoji: "👓" },
           { id: "274", english: "Regulation", japanese: "規則/規制", pronunciation: "レギュレイション", level: "advanced", category: "政治", emoji: "📜" },
           { id: "275", english: "Sustainability", japanese: "持続可能性", pronunciation: "サステイナビリティ", level: "advanced", category: "社会", emoji: "♻️" },
           { id: "276", english: "Transformation", japanese: "変容/変化", pronunciation: "トランスフォーメイション", level: "advanced", category: "抽象", emoji: "🦋" },
           { id: "277", english: "Utilization", japanese: "利用/活用", pronunciation: "ユーティライゼイション", level: "advanced", category: "ビジネス", emoji: "⚙️" },
           { id: "278", english: "Validation", japanese: "確認/批准", pronunciation: "ヴァリデイション", level: "advanced", category: "ビジネス", emoji: "✅" },
           { id: "279", english: "Welfare", japanese: "福祉/幸福", pronunciation: "ウェルフェア", level: "advanced", category: "社会", emoji: "🏥" },
           { id: "280", english: "Yield", japanese: "産出/収穫高", pronunciation: "イールド", level: "advanced", category: "ビジネス", emoji: "🌾" },
           { id: "281", english: "Abstract", japanese: "抽象的な", pronunciation: "アブストラクト", level: "advanced", category: "形容詞", emoji: "🎨" },
           { id: "282", english: "Burden", japanese: "負担/重荷", pronunciation: "バーデン", level: "advanced", category: "抽象", emoji: "🎒" },
           { id: "283", english: "Capability", japanese: "能力/素質", pronunciation: "ケイパビリティ", level: "advanced", category: "抽象", emoji: "💪" },
           { id: "284", english: "Depict", japanese: "描く/描写する", pronunciation: "ディピクト", level: "advanced", category: "動詞", emoji: "🎨" },
           { id: "285", english: "Enormous", japanese: "巨大な", pronunciation: "イノーマス", level: "advanced", category: "形容詞", emoji: "🦖" },
           { id: "286", english: "Fluctuate", japanese: "変動する/上下する", pronunciation: "フラクチュエイト", level: "advanced", category: "動詞", emoji: "📈" },
           { id: "287", english: "Guarantee", japanese: "保証", pronunciation: "ギャランティー", level: "advanced", category: "ビジネス", emoji: "🛡️" },
           { id: "288", english: "Hierarchy", japanese: "階層制", pronunciation: "ハイアラキー", level: "advanced", category: "社会", emoji: "👑" },
           { id: "289", english: "Implication", japanese: "含み/影響", pronunciation: "インプリケイション", level: "advanced", category: "思考", emoji: "💡" },
           { id: "290", english: "Jurisdiction", japanese: "司法権", pronunciation: "ジュリスディクション", level: "advanced", category: "政治", emoji: "⚖️" },
           { id: "291", english: "Legitimacy", japanese: "正当性", pronunciation: "レジティマシー", level: "advanced", category: "政治", emoji: "⚖️" },
           { id: "292", english: "Manifest", japanese: "明白にする/現れる", pronunciation: "マニフェスト", level: "advanced", category: "動詞", emoji: "📄" },
           { id: "293", english: "Notion", japanese: "概念/考え", pronunciation: "ノウション", level: "advanced", category: "思考", emoji: "🧠" },
           { id: "294", english: "Objective", japanese: "客観的な/目標", pronunciation: "オブジェクティヴ", level: "advanced", category: "思考", emoji: "🎯" },
           { id: "295", english: "Paradigm", japanese: "範例/パラダイム", pronunciation: "パラダイム", level: "advanced", category: "抽象", emoji: "💠" },
           { id: "296", english: "Quantitative", japanese: "量的な", pronunciation: "クオンティテイティヴ", level: "advanced", category: "形容詞", emoji: "🔢" },
           { id: "297", english: "Rational", japanese: "合理的な", pronunciation: "ラショナル", level: "advanced", category: "形容詞", emoji: "🧠" },
           { id: "298", english: "Speculate", japanese: "推測する/投機する", pronunciation: "スペキュレイト", level: "advanced", category: "動詞", emoji: "🧐" },
           { id: "299", english: "Terminology", japanese: "術語/用語", pronunciation: "ターミノロジー", level: "advanced", category: "学問", emoji: "📖" },
           { id: "300", english: "Undergo", japanese: "経験する/受ける", pronunciation: "アンダーゴウ", level: "advanced", category: "動詞", emoji: "🩹" },
           { id: "301", english: "Vulnerable", japanese: "脆弱な", pronunciation: "ヴァルネラブル", level: "advanced", category: "形容詞", emoji: "🛡️" },
           { id: "302", english: "Widespread", japanese: "普及した", pronunciation: "ワイドスプレッド", level: "advanced", category: "形容詞", emoji: "🌊" },
           { id: "303", english: "Acquire", japanese: "習得する/獲得する", pronunciation: "アクワイア", level: "advanced", category: "動詞", emoji: "🎒" },
           { id: "304", english: "Brief", japanese: "簡潔な/短い", pronunciation: "ブリーフ", level: "advanced", category: "形容詞", emoji: "📝" },
           { id: "305", english: "Consistent", japanese: "一貫した", pronunciation: "コンスィスタント", level: "advanced", category: "形容詞", emoji: "🔄" },
           { id: "306", english: "Diverse", japanese: "多様な", pronunciation: "ダイヴァース", level: "advanced", category: "形容詞", emoji: "🎨" },
           { id: "307", english: "Evaluate", japanese: "評価する", pronunciation: "イヴァリュエイト", level: "advanced", category: "動詞", emoji: "📊" },
           { id: "308", english: "Flexible", japanese: "柔軟な", pronunciation: "フレキシブル", level: "advanced", category: "形容詞", emoji: "🤸" },
           { id: "309", english: "Generate", japanese: "生み出す/発生させる", pronunciation: "ジェネレイト", level: "advanced", category: "動詞", emoji: "⚡" },
           { id: "310", english: "Highlight", japanese: "強調する/目立たせる", pronunciation: "ハイライト", level: "advanced", category: "動詞", emoji: "🖍️" },
           { id: "311", english: "Internal", japanese: "内部の", pronunciation: "インターナル", level: "advanced", category: "形容詞", emoji: "🏠" },
           { id: "312", english: "Logical", japanese: "論理的な", pronunciation: "ロジカル", level: "advanced", category: "形容詞", emoji: "🧠" },
           { id: "313", english: "Maximum", japanese: "最大の", pronunciation: "マクスィマム", level: "advanced", category: "形容詞", emoji: "📈" },
           { id: "314", english: "Negative", japanese: "否定的な/負の", pronunciation: "ネガティヴ", level: "advanced", category: "形容詞", emoji: "➖" },
           { id: "315", english: "Outcome", japanese: "結果/成果", pronunciation: "アウトカム", level: "advanced", category: "抽象", emoji: "🏁" },
           { id: "316", english: "Precise", japanese: "正確な/精密な", pronunciation: "プリスィス", level: "advanced", category: "形容詞", emoji: "🎯" },
           { id: "317", english: "Relevant", japanese: "関連のある", pronunciation: "レレヴァント", level: "advanced", category: "形容詞", emoji: "🔗" },
           { id: "318", english: "Significant", japanese: "重要な/かなりの", pronunciation: "スィグニフィカント", level: "advanced", category: "形容詞", emoji: "⭐" },
           { id: "319", english: "Unique", japanese: "独特な/唯一の", pronunciation: "ユニーク", level: "advanced", category: "形容詞", emoji: "🦄" },
           { id: "320", english: "Verify", japanese: "確かめる/立証する", pronunciation: "ヴェリファイ", level: "advanced", category: "動詞", emoji: "✅" },
           { id: "321", english: "Artificial", japanese: "人工的な", pronunciation: "アーティフィシャル", level: "advanced", category: "形容詞", emoji: "🤖" },
           { id: "322", english: "Bias", japanese: "偏見/バイアス", pronunciation: "バイアス", level: "advanced", category: "抽象", emoji: "⚖️" },
           { id: "323", english: "Complex", japanese: "複雑な", pronunciation: "コンプレックス", level: "advanced", category: "形容詞", emoji: "🧩" },
           { id: "324", english: "Deduce", japanese: "推論する", pronunciation: "ディデュース", level: "advanced", category: "動詞", emoji: "🧐" },
           { id: "325", english: "Equivalent", japanese: "同等の", pronunciation: "イクイヴァレント", level: "advanced", category: "形容詞", emoji: "＝" },
           { id: "326", english: "Fundamental", japanese: "根本的な/基礎の", pronunciation: "ファンダメンタル", level: "advanced", category: "形容詞", emoji: "🧱" },
           { id: "327", english: "Hypothetical", japanese: "仮定の", pronunciation: "ハイポスェティカル", level: "advanced", category: "形容詞", emoji: "🧪" },
           { id: "328", english: "Implicit", japanese: "暗黙の", pronunciation: "インプリスィット", level: "advanced", category: "形容詞", emoji: "🤫" },
           { id: "329", english: "Neutral", japanese: "中立の", pronunciation: "ニュートラル", level: "advanced", category: "形容詞", emoji: "⚪" },
           { id: "330", english: "Potential", japanese: "潜在的な/可能性", pronunciation: "ポテンシャル", level: "advanced", category: "形容詞", emoji: "🌱" },
           { id: "331", english: "Resource", japanese: "資源/財源", pronunciation: "リソース", level: "advanced", category: "社会", emoji: "💎" },
           { id: "332", english: "Stable", japanese: "安定した", pronunciation: "ステイブル", level: "advanced", category: "形容詞", emoji: "⚓" },
           { id: "333", english: "Ultimate", japanese: "究極の/最終的な", pronunciation: "アルティメット", level: "advanced", category: "形容詞", emoji: "🏁" },
           { id: "334", english: "Virtual", japanese: "実質上の/仮想の", pronunciation: "ヴァーチャル", level: "advanced", category: "形容詞", emoji: "🕶️" },
           { id: "335", english: "Attribute", japanese: "属性/〜のせいにする", pronunciation: "アトリビュート", level: "advanced", category: "抽象", emoji: "🏷️" },
           { id: "336", english: "Clause", japanese: "条項/節", pronunciation: "クロウズ", level: "advanced", category: "学問", emoji: "📜" },
           { id: "337", english: "Domain", japanese: "領域/分野", pronunciation: "ドメイン", level: "advanced", category: "社会", emoji: "🌐" },
           { id: "338", english: "Entity", japanese: "実体/存在物", pronunciation: "エンティティ", level: "advanced", category: "抽象", emoji: "👻" },
           { id: "339", english: "Fee", japanese: "料金/謝礼", pronunciation: "フィー", level: "advanced", category: "ビジネス", emoji: "💸" },
           { id: "340", english: "Gender", japanese: "性/ジェンダー", pronunciation: "ジェンダー", level: "advanced", category: "社会", emoji: "🚻" },
           { id: "341", english: "Incentive", japanese: "動機/刺激", pronunciation: "インセンティヴ", level: "advanced", category: "ビジネス", emoji: "🎁" },
           { id: "342", english: "Layer", japanese: "層/重なり", pronunciation: "レイヤー", level: "advanced", category: "抽象", emoji: "🍰" },
           { id: "343", english: "Marginal", japanese: "わずかな/辺境の", pronunciation: "マージナル", level: "advanced", category: "形容詞", emoji: "📉" },
           { id: "344", english: "Network", japanese: "ネットワーク/網", pronunciation: "ネットワーク", level: "advanced", category: "科学", emoji: "🌐" },
           { id: "345", english: "Orientation", japanese: "方向付け/適応", pronunciation: "オリエンテイション", level: "advanced", category: "ビジネス", emoji: "🧭" },
           { id: "346", english: "Phase", japanese: "段階/局面", pronunciation: "フェイズ", level: "advanced", category: "時間", emoji: "🌗" },
           { id: "347", english: "Ratio", japanese: "比率", pronunciation: "レイシオ", level: "advanced", category: "科学", emoji: "％" },
           { id: "348", english: "Scheme", japanese: "計画/スキーム", pronunciation: "スキーム", level: "advanced", category: "ビジネス", emoji: "📝" },
           { id: "349", english: "Target", japanese: "目標/標的", pronunciation: "ターゲット", level: "advanced", category: "ビジネス", emoji: "🎯" },
           { id: "350", english: "Underlie", japanese: "〜の根底にある", pronunciation: "アンダーライ", level: "advanced", category: "動詞", emoji: "🧱" },
           { id: "351", english: "Valid", japanese: "有効な/正当な", pronunciation: "ヴァリッド", level: "advanced", category: "形容詞", emoji: "✅" },
           { id: "352", english: "Welfare", japanese: "福利/生活保護", pronunciation: "ウェルフェア", level: "advanced", category: "社会", emoji: "🏥" },
           { id: "353", english: "Pragmatic", japanese: "実用的な/実利的な", pronunciation: "プラグマティック", level: "advanced", category: "形容詞", emoji: "🛠️" },
           { id: "354", english: "Quarantine", japanese: "検疫/隔離", pronunciation: "クアランティーン", level: "advanced", category: "社会", emoji: "🏥" },
           { id: "355", english: "Relinquish", japanese: "（権利などを）放棄する/譲渡する", pronunciation: "リリンクウィッシュ", level: "advanced", category: "動詞", emoji: "👐" },
           { id: "356", english: "Scrutinize", japanese: "詳細に調べる/吟味する", pronunciation: "スクルーティナイズ", level: "advanced", category: "動詞", emoji: "🔍" },
           { id: "357", english: "Tangible", japanese: "触れられる/具体的な/明白な", pronunciation: "タンジブル", level: "advanced", category: "形容詞", emoji: "🖐️" },
           { id: "358", english: "Ubiquitous", japanese: "至る所にある/遍在する", pronunciation: "ユビキタス", level: "advanced", category: "形容詞", emoji: "🌐" },
           { id: "359", english: "Validate", japanese: "有効にする/正当性を立証する", pronunciation: "バリデイト", level: "advanced", category: "動詞", emoji: "✅" },
           { id: "360", english: "Whimsical", japanese: "気まぐれな/一風変わった", pronunciation: "ウィムズィカル", level: "advanced", category: "形容詞", emoji: "🎈" },
           { id: "361", english: "Yield", japanese: "産出する/（利益を）生む/屈する", pronunciation: "イールド", level: "advanced", category: "動詞", emoji: "🌾" },
           { id: "362", english: "Zeal", japanese: "熱意/熱中", pronunciation: "ズィール", level: "advanced", category: "感情", emoji: "🔥" },
           { id: "363", english: "Ambiguous", japanese: "曖昧な/二通りの意味にとれる", pronunciation: "アンビギュアス", level: "advanced", category: "形容詞", emoji: "🌫️" },
           { id: "364", english: "Benevolent", japanese: "慈悲深い/善意ある", pronunciation: "ベネヴォレント", level: "advanced", category: "形容詞", emoji: "😇" },
           { id: "365", english: "Coherent", japanese: "首尾一貫した/筋の通った", pronunciation: "コウヒアラント", level: "advanced", category: "形容詞", emoji: "🔗" },
           { id: "366", english: "Detrimental", japanese: "有害な/不利益な", pronunciation: "デトリメンタル", level: "advanced", category: "形容詞", emoji: "⚠️" },
           { id: "367", english: "Eloquent", japanese: "雄弁な/説得力のある", pronunciation: "エロクウェント", level: "advanced", category: "形容詞", emoji: "🗣️" },
           { id: "368", english: "Fostering", japanese: "育成する/促進する", pronunciation: "フォスタリング", level: "advanced", category: "動詞", emoji: "🌱" },
           { id: "369", english: "Grievance", japanese: "不満/苦情", pronunciation: "グリーヴァンス", level: "advanced", category: "抽象", emoji: "😤" },
           { id: "370", english: "Hinder", japanese: "妨げる/遅らせる", pronunciation: "ヒンダー", level: "advanced", category: "動詞", emoji: "🚧" },
           { id: "371", english: "Implication", japanese: "暗示/影響/含み", pronunciation: "インプリケイション", level: "advanced", category: "思考", emoji: "💡" },
           { id: "372", english: "Jurisdiction", japanese: "司法権/管轄権", pronunciation: "ジュリスディクション", level: "advanced", category: "政治", emoji: "⚖️" },
           { id: "373", english: "Kindle", japanese: "（情熱などを）燃え立たせる/火をつける", pronunciation: "キンドル", level: "advanced", category: "動詞", emoji: "🔥" },
           { id: "374", english: "Lament", japanese: "嘆き悲しむ", pronunciation: "ラメント", level: "advanced", category: "動詞", emoji: "😢" },
           { id: "375", english: "Mitigate", japanese: "和らげる/軽減する", pronunciation: "ミティゲイト", level: "advanced", category: "動詞", emoji: "🩹" },
           { id: "376", english: "Nurture", japanese: "育む/養育する", pronunciation: "ナーチャー", level: "advanced", category: "動詞", emoji: "🌱" },
           { id: "377", english: "Obstinate", japanese: "頑固な/強情な", pronunciation: "オブスティネット", level: "advanced", category: "形容詞", emoji: "😤" },
           { id: "378", english: "Paradox", japanese: "逆説/パラドックス", pronunciation: "パラドックス", level: "advanced", category: "抽象", emoji: "🔄" },
           { id: "379", english: "Quench", japanese: "（渇きなどを）癒やす/抑える", pronunciation: "クエンチ", level: "advanced", category: "動詞", emoji: "🥤" },
           { id: "380", english: "Relentless", japanese: "容赦ない/執拗な", pronunciation: "リレントレス", level: "advanced", category: "形容詞", emoji: "⛓️" },
           { id: "381", english: "Stagnant", japanese: "停滞した/淀んだ", pronunciation: "スタグナント", level: "advanced", category: "形容詞", emoji: "💧" },
           { id: "382", english: "Trivial", japanese: "些細な/ありふれた", pronunciation: "トリヴィアル", level: "advanced", category: "形容詞", emoji: "🔍" },
           { id: "383", english: "Unanimous", japanese: "満場一致の", pronunciation: "ユナニマス", level: "advanced", category: "形容詞", emoji: "🙋" },
           { id: "384", english: "Versatile", japanese: "多才な/万能な", pronunciation: "ヴァサタイル", level: "advanced", category: "形容詞", emoji: "🔧" },
           { id: "385", english: "Warrant", japanese: "正当な理由/保証する", pronunciation: "ウォラント", level: "advanced", category: "抽象", emoji: "🛡️" },
           { id: "386", english: "Xenophobia", japanese: "外国人嫌悪", pronunciation: "ゼノフォビア", level: "advanced", category: "社会", emoji: "🚫" },
           { id: "387", english: "Yearn", japanese: "切望する/憧れる", pronunciation: "ヤーン", level: "advanced", category: "動詞", emoji: "🌟" },
           { id: "388", english: "Zenith", japanese: "頂点/絶頂", pronunciation: "ゼニス", level: "advanced", category: "抽象", emoji: "🏔️" },
           { id: "389", english: "Authentic", japanese: "本物の/信頼できる", pronunciation: "オーセンティック", level: "advanced", category: "形容詞", emoji: "💎" },
           { id: "390", english: "Cognizant", japanese: "認識している/知っている", pronunciation: "コグニザント", level: "advanced", category: "形容詞", emoji: "🧠" },
           { id: "391", english: "Deviate", japanese: "（進路などから）外れる/逸れる", pronunciation: "ディヴィエイト", level: "advanced", category: "動詞", emoji: "↪️" },
           { id: "392", english: "Equitable", japanese: "公平な/正当な", pronunciation: "エクイタブル", level: "advanced", category: "形容詞", emoji: "⚖️" },
           { id: "393", english: "Advocate", japanese: "主張する/支持者", pronunciation: "アドヴォケイト", level: "advanced", category: "動詞", emoji: "📢" },
           { id: "394", english: "Compliment", japanese: "褒め言葉", pronunciation: "コンプリメント", level: "advanced", category: "抽象", emoji: "👏" },
           { id: "395", english: "Dilemma", japanese: "板挟み/ジレンマ", pronunciation: "ディレンマ", level: "advanced", category: "抽象", emoji: "🤔" },
           { id: "396", english: "Exaggerate", japanese: "誇張する", pronunciation: "イグザジェレイト", level: "advanced", category: "動詞", emoji: "📢" },
           { id: "397", english: "Flourish", japanese: "繁栄する", pronunciation: "フラリッシュ", level: "advanced", category: "動詞", emoji: "🌸" },
           { id: "398", english: "Gratitude", japanese: "感謝", pronunciation: "グラティテュード", level: "advanced", category: "感情", emoji: "🙏" },
           { id: "399", english: "Hostile", japanese: "敵対的な", pronunciation: "ホスタイル", level: "advanced", category: "形容詞", emoji: "👊" },
           { id: "400", english: "Inevitably", japanese: "必然的に", pronunciation: "イネヴィタブリー", level: "advanced", category: "副詞", emoji: "➡️" },
           { id: "401", english: "Jovial", japanese: "陽気な", pronunciation: "ジョヴィアル", level: "advanced", category: "形容詞", emoji: "😄" },
           { id: "402", english: "Lethargic", japanese: "無気力な", pronunciation: "レザージック", level: "advanced", category: "形容詞", emoji: "😴" },
           { id: "403", english: "Meticulous", japanese: "細心の注意を払った", pronunciation: "メティキュラス", level: "advanced", category: "形容詞", emoji: "🔍" },
           { id: "404", english: "Naive", japanese: "世間知らずな/純真な", pronunciation: "ナイーヴ", level: "advanced", category: "形容詞", emoji: "🐣" },
           { id: "405", english: "Omission", japanese: "省略/手落", pronunciation: "オミッション", level: "advanced", category: "抽象", emoji: "✂️" },
           { id: "406", english: "Pessimism", japanese: "悲観主義", pronunciation: "ペスィミズム", level: "advanced", category: "抽象", emoji: "🌑" },
           { id: "407", english: "Reciprocal", japanese: "相互の", pronunciation: "レシプロカル", level: "advanced", category: "形容詞", emoji: "🔄" },
           { id: "408", english: "Skeptical", japanese: "懐疑的な", pronunciation: "スケプティカル", level: "advanced", category: "形容詞", emoji: "🤨" },
           { id: "409", english: "Thrive", japanese: "繁盛する", pronunciation: "スライヴ", level: "advanced", category: "動詞", emoji: "📈" },
           { id: "410", english: "Unprecedented", japanese: "前例のない", pronunciation: "アンプレセデンティッド", level: "advanced", category: "形容詞", emoji: "🆕" },
           { id: "411", english: "Vibrant", japanese: "活気のある", pronunciation: "ヴァイブラント", level: "advanced", category: "形容詞", emoji: "🎉" }
         ];
         
         const grammarQuestions = [
           // --- 初級：中1レベル (ID: g1 - g33) ---
           { id: "g1", question: "I ___ a student.", options: ["am", "is", "are", "be"], correct: 0, explanation: "主語が'I'なので、be動詞は'am'を使います。", level: "beginner" },
           { id: "g2", question: "She ___ my sister.", options: ["am", "is", "are", "be"], correct: 1, explanation: "主語が'She'（三人称単数）なので、be動詞は'is'を使います。", level: "beginner" },
           { id: "g3", question: "I ___ to school every day.", options: ["go", "goes", "going", "went"], correct: 0, explanation: "主語が'I'なので、現在形の'go'を使います。", level: "beginner" },
           { id: "g4", question: "He ___ English.", options: ["study", "studys", "studies", "studying"], correct: 2, explanation: "三人称単数の主語（He）なので、動詞に's'または'es'をつけます。", level: "beginner" },
           { id: "g5", question: "___ you like pizza?", options: ["Do", "Does", "Are", "Is"], correct: 0, explanation: "主語が'you'なので、疑問文は'Do'を使います。", level: "beginner" },
           { id: "g6", question: "She ___ not play tennis.", options: ["do", "does", "is", "are"], correct: 1, explanation: "三人称単数の否定文は'does not'を使います。", level: "beginner" },
           { id: "g7", question: "This is ___ book.", options: ["I", "my", "me", "mine"], correct: 1, explanation: "名詞の前には所有格'my'を使います。", level: "beginner" },
           { id: "g8", question: "Action Mask ___ my hero!", options: ["am", "is", "are", "be"], correct: 1, explanation: "アクション仮面は一人（三人称単数）なので 'is' だゾ！", level: "beginner" },
           { id: "g9", question: "I ___ green peppers (ピーマン).", options: ["don't like", "doesn't like", "not like", "am not like"], correct: 0, explanation: "オラ、ピーマンは食べたくないゾ。主語が I だから 'don't like' だね。", level: "beginner" },
           { id: "g10", question: "What ___ this?", options: ["am", "is", "are", "be"], correct: 1, explanation: "「これは何？」と聞くときは 'is' を使うんだゾ。", level: "beginner" },
           { id: "g11", question: "I have two ___.", options: ["apple", "apples", "an apple", "applees"], correct: 1, explanation: "2つ以上あるときは名詞に 's' をつけるんだゾ。複数形だゾ！", level: "beginner" },
           { id: "g12", question: "How ___ are you? - I'm five years old.", options: ["old", "many", "much", "tall"], correct: 0, explanation: "年齢を聞くときは 'How old' を使うんだゾ。オラは5歳だゾ！", level: "beginner" },
           { id: "g13", question: "Let's ___ soccer!", options: ["play", "plays", "playing", "played"], correct: 0, explanation: "Let's の後は動詞の原形が来るんだゾ。一緒に遊ぼうゾ！", level: "beginner" },
           { id: "g14", question: "Who ___ that man?", options: ["am", "is", "are", "be"], correct: 1, explanation: "「あの男の人は誰？」という疑問文。一人だから 'is' だゾ。", level: "beginner" },
           { id: "g15", question: "I can ___ fast.", options: ["run", "runs", "running", "ran"], correct: 0, explanation: "助動詞 can の後は動詞の原形がくるルールだゾ。", level: "beginner" },
           { id: "g16", question: "Is that your car? - Yes, ___.", options: ["it is", "it am", "you are", "I am"], correct: 0, explanation: "that で聞かれたら it で答えるのが基本だゾ。", level: "beginner" },
           { id: "g17", question: "There ___ a book on the desk.", options: ["am", "is", "are", "be"], correct: 1, explanation: "「〜がある」という時、単数なら 'There is' だゾ。", level: "beginner" },
           { id: "g18", question: "We ___ happy today.", options: ["am", "is", "are", "be"], correct: 2, explanation: "主語が We（複数）だから、be動詞は 'are' になるゾ。", level: "beginner" },
           { id: "g19", question: "Wash your hands ___ dinner.", options: ["before", "after", "at", "to"], correct: 0, explanation: "「夕食の前に」手を洗うから 'before' が正解だゾ。綺麗にするゾ！", level: "beginner" },
           { id: "g20", question: "Do you have ___ pens?", options: ["some", "any", "a", "one"], correct: 1, explanation: "疑問文で「いくつかの〜」と聞くときは 'any' を使うことが多いんだゾ。", level: "beginner" },
           { id: "g21", question: "___ you from Japan?", options: ["Am", "Is", "Are", "Do"], correct: 2, explanation: "出身を聞く疑問文は Are を使うんだゾ。オラは春日部出身だゾ！", level: "beginner" },
           { id: "g22", question: "These ___ my favorite Chocobi.", options: ["am", "is", "are", "be"], correct: 2, explanation: "These（これら）は複数だから be動詞は are だゾ！チョコビがいっぱいだゾ！", level: "beginner" },
           { id: "g23", question: "Look ___ that bird!", options: ["at", "to", "in", "on"], correct: 0, explanation: "「〜を見て」という時は look at を使うんだゾ。シロも見てるゾ。", level: "beginner" },
           { id: "g24", question: "I ___ breakfast every morning.", options: ["eat", "eats", "eating", "eaten"], correct: 0, explanation: "毎朝の習慣は現在形。主語が I だから eat そのままだゾ。", level: "beginner" },
           { id: "g25", question: "Does your father ___ a car?", options: ["drive", "drives", "driving", "drove"], correct: 0, explanation: "疑問文の Does が前に出たら、動詞は原形に戻るんだゾ。父ちゃん頑張れだゾ！", level: "beginner" },
           { id: "g26", question: "Ken ___ basketball every Sunday.", options: ["play", "plays", "playing", "played"], correct: 1, explanation: "Kenは三人称単数だから動詞に s がつくんだゾ。シュートだゾ！", level: "beginner" },
           { id: "g27", question: "I study English ___ night.", options: ["in", "on", "at", "to"], correct: 2, explanation: "夜に、という時は at night と言うのがお約束だゾ。", level: "beginner" },
           { id: "g28", question: "Open the window, ___.", options: ["please", "thank you", "hello", "sorry"], correct: 0, explanation: "「〜してください」と頼むときは please をつけるんだゾ。", level: "beginner" },
           { id: "g29", question: "This is a pen. ___ is red.", options: ["He", "She", "It", "They"], correct: 2, explanation: "物を指すときは It を使うんだゾ。これは赤ペンだゾ。", level: "beginner" },
           { id: "g30", question: "Whose book is this? - It's ___.", options: ["me", "my", "mine", "I"], correct: 2, explanation: "「私のもの」と言いたいときは mine を使うんだゾ。オラのじゃないゾ。", level: "beginner" },
           { id: "g31", question: "Where ___ you go yesterday?", options: ["do", "does", "did", "are"], correct: 2, explanation: "「昨日」のことを聞くときは過去形の did を使うんだゾ。", level: "beginner" },
           { id: "g32", question: "How ___ is this Chocobi? - It's 100 yen.", options: ["much", "many", "old", "tall"], correct: 0, explanation: "値段を聞くときは How much だゾ。チョコビ食べたいゾ〜。", level: "beginner" },
           { id: "g33", question: "I don't have ___ money.", options: ["some", "any", "a", "one"], correct: 1, explanation: "否定文で「少しも〜ない」という時は any を使うんだゾ。お小遣いピンチだゾ！", level: "beginner" },
         
           // --- 中級：中2レベル (ID: g34 - g66) ---
           { id: "g34", question: "Shiro ___ around.", options: ["run", "runs", "is running", "ran"], correct: 2, explanation: "シロが今まさに走り回ってる（わたあめ！）から、現在進行形の 'is running' だゾ。", level: "intermediate" },
           { id: "g35", question: "Mom, you ___ buy some Chocobi for me.", options: ["must", "musts", "are must", "must to"], correct: 0, explanation: "「チョコビを買わなきゃダメだゾ！」という強い意志（命令？）は 'must' を使うんだゾ。", level: "intermediate" },
           { id: "g36", question: "They ___ to Tokyo last year.", options: ["go", "goes", "went", "going"], correct: 2, explanation: "'last year'があるので、過去形'went'を使います。", level: "intermediate" },
           { id: "g37", question: "She ___ a book now.", options: ["read", "reads", "is reading", "reading"], correct: 2, explanation: "'now'があるので、現在進行形'is reading'を使います。", level: "intermediate" },
           { id: "g38", question: "I will ___ to America next month.", options: ["go", "goes", "went", "going"], correct: 0, explanation: "'will'の後は動詞の原形が来ます。", level: "intermediate" },
           { id: "g39", question: "He ___ play the guitar.", options: ["can", "cans", "is can", "can to"], correct: 0, explanation: "助動詞'can'の後は動詞の原形が来ます。", level: "intermediate" },
           { id: "g40", question: "You ___ study hard for the test.", options: ["must", "musts", "must to", "are must"], correct: 0, explanation: "助動詞'must'の後は動詞の原形が来ます。", level: "intermediate" },
           { id: "g41", question: "This book is ___ than that one.", options: ["interesting", "more interesting", "most interesting", "interestinger"], correct: 1, explanation: "3音節以上の形容詞の比較級は'more + 形容詞'の形になります。", level: "intermediate" },
           { id: "g42", question: "She is ___ student in our class.", options: ["tall", "taller", "the tallest", "most tall"], correct: 2, explanation: "最上級は'the + 形容詞est'の形になります。", level: "intermediate" },
           { id: "g43", question: "If it ___ tomorrow, I will stay home.", options: ["rain", "rains", "will rain", "rained"], correct: 1, explanation: "if節（時や条件を表す副詞節）の中では、未来のことでも現在形を使うんだゾ。", level: "intermediate" },
           { id: "g44", question: "I was ___ TV when you called me.", options: ["watch", "watches", "watching", "watched"], correct: 2, explanation: "「〜していた時」という過去進行形。be動詞の過去形 + ingだゾ。", level: "intermediate" },
           { id: "g45", question: "You don't ___ to go if you are tired.", options: ["must", "have", "need", "can"], correct: 1, explanation: "「〜する必要はない」は don't have to だゾ。ゆっくり休むんだゾ。", level: "intermediate" },
           { id: "g46", question: "He is as ___ as his father.", options: ["tall", "taller", "tallest", "more tall"], correct: 0, explanation: "as 〜 as の間には、形容詞の「原形」を入れるルールだゾ。", level: "intermediate" },
           { id: "g47", question: "I ___ to be a pilot in the future.", options: ["want", "hope", "will", "am"], correct: 0, explanation: "「〜になりたい」は want to be 〜 だゾ。未来の夢だゾ！", level: "intermediate" },
           { id: "g48", question: "Which do you like ___ , apples or oranges?", options: ["better", "best", "good", "well"], correct: 0, explanation: "2つのものを比べて「どちらが好きか」聞く時は better を使うんだゾ。", level: "intermediate" },
           { id: "g49", question: "There are many ___ to visit in Nara.", options: ["place", "places", "placed", "placing"], correct: 1, explanation: "many の後は名詞の複数形。奈良には良いところがたくさんあるゾ。", level: "intermediate" },
           { id: "g50", question: "I am ___ in Japanese history.", options: ["interest", "interesting", "interested", "interests"], correct: 2, explanation: "「〜に興味がある」は be interested in 〜 と言うんだゾ。勉強家だゾ！", level: "intermediate" },
           { id: "g51", question: "I'll call you when I ___ home.", options: ["get", "gets", "will get", "got"], correct: 0, explanation: "「〜した時」という副詞節の中は、未来のことでも現在形を使うんだゾ。", level: "intermediate" },
           { id: "g52", question: "Shall we ___ lunch now?", options: ["have", "has", "having", "had"], correct: 0, explanation: "Shall we 〜?（〜しませんか）の後は動詞の原形だゾ。お腹空いたゾ。", level: "intermediate" },
           { id: "g53", question: "You ___ not eat too much candy.", options: ["should", "would", "shall", "will"], correct: 0, explanation: "「〜すべきではない」とアドバイスする時は should を使うんだゾ。", level: "intermediate" },
           { id: "g54", question: "I think ___ she is a good teacher.", options: ["that", "which", "what", "who"], correct: 0, explanation: "「〜だと思う」という文をつなぐ接続詞の that だゾ。省略もできるゾ。", level: "intermediate" },
           { id: "g55", question: "It's ___ to speak English.", options: ["hard", "hardly", "harder", "hardest"], correct: 0, explanation: "「英語を話すのは大変だ」という文。It is 形容詞 to 〜 の形だゾ。", level: "intermediate" },
           { id: "g56", question: "I finished ___ my homework.", options: ["do", "to do", "doing", "did"], correct: 2, explanation: "finish の後は動名詞（-ing形）がくるルールだゾ。やっと終わったゾ！", level: "intermediate" },
           { id: "g57", question: "___ you ever been to Hokkaido?", options: ["Do", "Did", "Have", "Are"], correct: 2, explanation: "「行ったことがありますか？」という経験を聞く現在完了形（Have + 過去分詞）だゾ。", level: "intermediate" },
           { id: "g58", question: "I have lived in Kasukabe ___ five years.", options: ["since", "for", "during", "at"], correct: 1, explanation: "期間（5年間）を表す時は for を使うんだゾ。ずっと住んでるゾ。", level: "intermediate" },
           { id: "g59", question: "My mother ___ me to clean my room.", options: ["said", "told", "spoke", "talked"], correct: 1, explanation: "「（人に）〜するように言う」は tell 人 to 〜 を使うんだゾ。怒られたゾ。", level: "intermediate" },
           { id: "g60", question: "It ___ raining since this morning.", options: ["is", "was", "has been", "been"], correct: 2, explanation: "「朝からずっと降っている」という現在完了進行形（have been -ing）だゾ。", level: "intermediate" },
           { id: "g61", question: "This cake was ___ by my sister.", options: ["make", "makes", "made", "making"], correct: 2, explanation: "「〜によって作られた」という受動態（be動詞 + 過去分詞）だゾ。美味しそうだゾ！", level: "intermediate" },
           { id: "g62", question: "I don't know ___ to do.", options: ["what", "who", "where", "when"], correct: 0, explanation: "「何をすべきか」という疑問詞 + 不定詞（to 〜）の形だゾ。困ったゾ。", level: "intermediate" },
           { id: "g63", question: "May I ___ your pen?", options: ["use", "uses", "using", "used"], correct: 0, explanation: "May I 〜?（〜してもいいですか？）の後は動詞の原形だゾ。借りるゾ。", level: "intermediate" },
           { id: "g64", question: "Would you like ___ water?", options: ["some", "any", "a", "the"], correct: 0, explanation: "「〜はいかがですか？」と勧める疑問文では some を使うのが一般的だゾ。", level: "intermediate" },
           { id: "g65", question: "I have to ___ my brother today.", options: ["help", "helps", "helping", "helped"], correct: 0, explanation: "have to 〜（〜しなければならない）の後は動詞の原形だゾ。お兄ちゃんだゾ。", level: "intermediate" },
           { id: "g66", question: "Could you ___ me the way to the station?", options: ["tell", "say", "speak", "talk"], correct: 0, explanation: "「道を教えて」という時は tell を使うんだゾ。丁寧なお願いだゾ。", level: "intermediate" },
         
           // --- 上級：中3・高校基礎レベル (ID: g67 - g100) ---
           { id: "g67", question: "I have ___ Chocobi many times.", options: ["eat", "ate", "eating", "eaten"], correct: 3, explanation: "「何度も食べたことがあるゾ」という経験は現在完了形（have + 過去分詞）だゾ！", level: "advanced" },
           { id: "g68", question: "Nanako-oneesan is the person ___ I love most.", options: ["who", "which", "where", "when"], correct: 0, explanation: "ななこおねえさんは「人」だから、関係代名詞は 'who' が正解だゾ〜。", level: "advanced" },
           { id: "g69", question: "I have ___ this book before.", options: ["read", "reading", "reads", "readed"], correct: 0, explanation: "現在完了形は'have + 過去分詞'の形です。'read'の過去分詞も'read'です。", level: "advanced" },
           { id: "g70", question: "This is the bag ___ I bought yesterday.", options: ["who", "which", "where", "when"], correct: 1, explanation: "物を説明する関係代名詞は'which'または'that'を使います。", level: "advanced" },
           { id: "g71", question: "I want ___ a doctor.", options: ["be", "to be", "being", "am"], correct: 1, explanation: "'want'の後は'to + 動詞の原形'（不定詞）が来ます。", level: "advanced" },
           { id: "g72", question: "I enjoy ___ music.", options: ["listen to", "listening to", "to listen", "listened to"], correct: 1, explanation: "'enjoy'の後は動名詞（-ing形）が来ます。", level: "advanced" },
           { id: "g73", question: "English ___ spoken in many countries.", options: ["is", "are", "be", "being"], correct: 0, explanation: "受動態は'be動詞 + 過去分詞'の形です。主語が'English'なので'is'を使います。", level: "advanced" },
           { id: "g74", question: "I don't know ___ he lives.", options: ["where", "what", "who", "which"], correct: 0, explanation: "「彼がどこに住んでいるか」という間接疑問文の語順（疑問詞 + 主語 + 動詞）だゾ。", level: "advanced" },
           { id: "g75", question: "The boy ___ under the tree is my friend.", options: ["sleep", "sleeping", "sleeps", "slept"], correct: 1, explanation: "「木の下で眠っている（少年）」という現在分詞の後置修飾だゾ。ぐーぐーだゾ。", level: "advanced" },
           { id: "g76", question: "He made me ___ my homework.", options: ["do", "to do", "doing", "did"], correct: 0, explanation: "使役動詞 make + 人 + 動詞の原形（人に〜させる）という形だゾ。厳しいゾ。", level: "advanced" },
           { id: "g77", question: "If I ___ rich, I would buy a big house.", options: ["am", "is", "was", "were"], correct: 3, explanation: "「もし〜なら」という現在の事実に反する仮定法過去。be動詞は were を使うのが基本だゾ。", level: "advanced" },
           { id: "g78", question: "I want you ___ some milk.", options: ["buy", "to buy", "buying", "bought"], correct: 1, explanation: "「あなたに〜してほしい」という時は want 人 to 〜 の形を使うんだゾ。", level: "advanced" },
           { id: "g79", question: "This is the most beautiful picture ___ I have ever seen.", options: ["that", "who", "what", "whose"], correct: 0, explanation: "最上級がある時は、関係代名詞は that を使うのが好まれるんだゾ。", level: "advanced" },
           { id: "g80", question: "It is important ___ us to protect nature.", options: ["to", "for", "at", "on"], correct: 1, explanation: "「（人にとって）〜することは重要だ」は It is ... for 人 to 〜 だゾ。大事だゾ。", level: "advanced" },
           { id: "g81", question: "I've just ___ my lunch.", options: ["finish", "finishing", "finished", "finishes"], correct: 2, explanation: "「ちょうど〜し終えた」という完了。have just + 過去分詞だゾ。満腹だゾ！", level: "advanced" },
           { id: "g82", question: "I'm looking forward to ___ you.", options: ["see", "seeing", "saw", "seen"], correct: 1, explanation: "look forward to の to は前置詞だから、後ろは動名詞 (-ing) がくるんだゾ。", level: "advanced" },
           { id: "g83", question: "She told me that she ___ busy.", options: ["is", "was", "has been", "be"], correct: 1, explanation: "主節が過去形 (told) なら、that節の中も過去形 (was) に合わせる時制の一致だゾ。", level: "advanced" },
           { id: "g84", question: "He is rich enough ___ a car.", options: ["buy", "buying", "to buy", "bought"], correct: 2, explanation: "「〜するのに十分なほど〜だ」という enough to 〜 の形だゾ。お金持ちだゾ〜。", level: "advanced" },
           { id: "g85", question: "The movie made her ___ .", options: ["cry", "to cry", "crying", "cried"], correct: 0, explanation: "使役動詞 make + 人 + 原形。「映画が彼女を泣かせた」という意味だゾ。", level: "advanced" },
           { id: "g86", question: "I forgot ___ the door.", options: ["lock", "to lock", "locking", "locked"], correct: 1, explanation: "「〜するのを忘れる（未来のこと）」は forget to 〜 を使うんだゾ。うっかりだゾ！", level: "advanced" },
           { id: "g87", question: "You've seen this movie, ___ ?", options: ["don't you", "haven't you", "aren't you", "did you"], correct: 1, explanation: "「〜ですね？」と確認する付加疑問文。現在完了の文だから haven't you だゾ。", level: "advanced" },
           { id: "g88", question: "I wish I ___ play the piano.", options: ["can", "could", "will", "may"], correct: 1, explanation: "「〜できればいいのになあ」という仮定法。助動詞も過去形 (could) にするんだゾ。", level: "advanced" },
           { id: "g89", question: "The woman ___ in that house is a teacher.", options: ["live", "lives", "living", "lived"], correct: 2, explanation: "「〜に住んでいる（女性）」と後ろから説明する現在分詞 (-ing) の形だゾ。", level: "advanced" },
           { id: "g90", question: "I used to ___ soccer when I was a child.", options: ["play", "playing", "played", "plays"], correct: 0, explanation: "used to 〜 で「以前はよく〜したものだ」という過去の習慣を表すゾ。今は寝てるゾ。", level: "advanced" },
           { id: "g91", question: "No other river is ___ than the Nile.", options: ["long", "longer", "longest", "the longest"], correct: 1, explanation: "「他のどの川もナイル川より長くはない」という比較級を使った最上級の意味だゾ。", level: "advanced" },
           { id: "g92", question: "He speaks English as if he ___ an American.", options: ["is", "was", "were", "am"], correct: 2, explanation: "「まるで〜であるかのように」という as if + 仮定法。be動詞は were を使うゾ。", level: "advanced" },
           { id: "g93", question: "It has been ten years ___ I left Japan.", options: ["for", "since", "during", "at"], correct: 1, explanation: "「日本を離れてから10年になる」という since を使った表現だゾ。懐かしいゾ。", level: "advanced" },
           { id: "g94", question: "Can you tell me how ___ to the museum?", options: ["go", "going", "to go", "goes"], correct: 2, explanation: "「どうやって行くか」という 疑問詞 + 不定詞 (to 〜) の形だゾ。教えてゾ。", level: "advanced" },
           { id: "g95", question: "___ a beautiful flower this is!", options: ["What", "How", "Which", "Who"], correct: 0, explanation: "「なんて美しい花なんだ！」という感嘆文。What a (形容詞) (名詞) ! の形だゾ。", level: "advanced" },
           { id: "g96", question: "The news made us ___ .", options: ["surprising", "surprised", "surprise", "surprises"], correct: 1, explanation: "「そのニュースは私たちを驚かせた」。make 人 過去分詞 の形だゾ。びっくりだゾ！", level: "advanced" },
           { id: "g97", question: "I don't know whether he ___ come tomorrow.", options: ["will", "is", "does", "did"], correct: 0, explanation: "「彼が明日来るかどうか」。whether節（名詞節）の中では未来の will を使うんだゾ。", level: "advanced" },
           { id: "g98", question: "Everything ___ I told you is true.", options: ["who", "which", "that", "whose"], correct: 2, explanation: "先行詞に everything がある時は、関係代名詞は that がよく使われるんだゾ。", level: "advanced" },
           { id: "g99", question: "Would you mind ___ the window?", options: ["open", "to open", "opening", "opened"], correct: 2, explanation: "「窓を開けていただけますか？」 mind の後は動名詞 (-ing) がくるルールだゾ。", level: "advanced" },
           { id: "g100", question: "He is said ___ a great actor.", options: ["be", "to be", "being", "is"], correct: 1, explanation: "「彼は偉大な俳優だと言われている」という be said to be 〜 の形だゾ。ついに100問だゾ！", level: "advanced" },
         ];